combination = {
    'sheet'    'freq_mtmfft_fourier_trl'       'DICS_keepall'             
    'sheet'    'freq_mtmfft_fourier_trl'       'DICS_keepall_rawtrial'    
    'sheet'    'freq_mtmfft_fourier_trl'       'DICS_keepnothing'         
    'sheet'    'freq_mtmfft_fourier_trl'       'DICS_keepnothing_rawtrial'
    'sheet'    'freq_mtmfft_fourier_trl'       'DICS_refdip'              
    'sheet'    'freq_mtmfft_fourier_trl'       'DICS_refchan'             
    'sheet'    'freq_mtmfft_fourier_trl'       'DICS_realfilter'          
    'sheet'    'freq_mtmfft_fourier_trl'       'DICS_fixedori'            
    'sheet'    'freq_mtmfft_fourier_trl'       'MNE_keepall'              
    'sheet'    'freq_mtmfft_fourier_trl'       'MNE_keepnothing'          
    'sheet'    'freq_mtmfft_fourier_trl'       'MNE_keepall_rawtrial'     
    'sheet'    'freq_mtmfft_fourier_trl'       'MNE_keepnothing_rawtrial' 
    'sheet'    'freq_mtmfft_fourier_trl'       'DICS_keepall'             
    'sheet'    'freq_mtmfft_fourier_trl'       'DICS_keepall_rawtrial'    
    'sheet'    'freq_mtmfft_fourier_trl'       'DICS_keepnothing'         
    'sheet'    'freq_mtmfft_fourier_trl'       'DICS_keepnothing_rawtrial'
    'sheet'    'freq_mtmfft_fourier_trl'       'DICS_refdip'              
    'sheet'    'freq_mtmfft_fourier_trl'       'DICS_refchan'             
    'sheet'    'freq_mtmfft_fourier_trl'       'DICS_realfilter'          
    'sheet'    'freq_mtmfft_fourier_trl'       'DICS_fixedori'            
    'sheet'    'freq_mtmfft_fourier_trl'       'PCC_keepall'              
    'sheet'    'freq_mtmfft_fourier_trl'       'PCC_keepall_rawtrial'     
    'sheet'    'freq_mtmfft_fourier_trl'       'PCC_keepnothing'          
    'sheet'    'freq_mtmfft_fourier_trl'       'PCC_keepnothing_rawtrial' 
    'sheet'    'freq_mtmfft_fourier_trl'       'PCC_refdip'               
    'sheet'    'freq_mtmconvol_fourier_trl'    'DICS_keepall'             
    'sheet'    'freq_mtmconvol_fourier_trl'    'DICS_keepall_rawtrial'    
    'sheet'    'freq_mtmconvol_fourier_trl'    'DICS_keepnothing'         
    'sheet'    'freq_mtmconvol_fourier_trl'    'DICS_keepnothing_rawtrial'
    'sheet'    'freq_mtmconvol_fourier_trl'    'DICS_refdip'              
    'sheet'    'freq_mtmconvol_fourier_trl'    'DICS_refchan'             
    'sheet'    'freq_mtmconvol_fourier_trl'    'DICS_realfilter'          
    'sheet'    'freq_mtmconvol_fourier_trl'    'DICS_fixedori'            
    'sheet'    'freq_mtmconvol_fourier_trl'    'MNE_keepall'              
    'sheet'    'freq_mtmconvol_fourier_trl'    'MNE_keepnothing'          
    'sheet'    'freq_mtmconvol_fourier_trl'    'MNE_keepall_rawtrial'     
    'sheet'    'freq_mtmconvol_fourier_trl'    'MNE_keepnothing_rawtrial' 
    'sheet'    'freq_mtmconvol_fourier_trl'    'DICS_keepall'             
    'sheet'    'freq_mtmconvol_fourier_trl'    'DICS_keepall_rawtrial'    
    'sheet'    'freq_mtmconvol_fourier_trl'    'DICS_keepnothing'         
    'sheet'    'freq_mtmconvol_fourier_trl'    'DICS_keepnothing_rawtrial'
    'sheet'    'freq_mtmconvol_fourier_trl'    'DICS_refdip'              
    'sheet'    'freq_mtmconvol_fourier_trl'    'DICS_refchan'             
    'sheet'    'freq_mtmconvol_fourier_trl'    'DICS_realfilter'          
    'sheet'    'freq_mtmconvol_fourier_trl'    'DICS_fixedori'            
    'sheet'    'freq_mtmconvol_fourier_trl'    'PCC_keepall'              
    'sheet'    'freq_mtmconvol_fourier_trl'    'PCC_keepall_rawtrial'     
    'sheet'    'freq_mtmconvol_fourier_trl'    'PCC_keepnothing'          
    'sheet'    'freq_mtmconvol_fourier_trl'    'PCC_keepnothing_rawtrial' 
    'sheet'    'freq_mtmconvol_fourier_trl'    'PCC_refdip'               
%    'sheet'    'freq_mtmfft_trl'               'DICS_keepall'             
%    'sheet'    'freq_mtmfft_trl'               'DICS_keepall_rawtrial'    
%    'sheet'    'freq_mtmfft_trl'               'DICS_keepnothing'         
%    'sheet'    'freq_mtmfft_trl'               'DICS_keepnothing_rawtrial'
%    'sheet'    'freq_mtmfft_trl'               'DICS_refdip'              
%    'sheet'    'freq_mtmfft_trl'               'DICS_refchan'             
%    'sheet'    'freq_mtmfft_trl'               'DICS_realfilter'          
%    'sheet'    'freq_mtmfft_trl'               'DICS_fixedori'            
%    'sheet'    'freq_mtmfft_trl'               'MNE_keepall'              
%    'sheet'    'freq_mtmfft_trl'               'MNE_keepnothing'          
%    'sheet'    'freq_mtmfft_trl'               'MNE_keepall_rawtrial'     
%    'sheet'    'freq_mtmfft_trl'               'MNE_keepnothing_rawtrial' 
%    'sheet'    'freq_mtmfft_trl'               'DICS_keepall'             
%    'sheet'    'freq_mtmfft_trl'               'DICS_keepall_rawtrial'    
%    'sheet'    'freq_mtmfft_trl'               'DICS_keepnothing'         
%    'sheet'    'freq_mtmfft_trl'               'DICS_keepnothing_rawtrial'
%    'sheet'    'freq_mtmfft_trl'               'DICS_refdip'              
%    'sheet'    'freq_mtmfft_trl'               'DICS_refchan'             
%    'sheet'    'freq_mtmfft_trl'               'DICS_realfilter'          
%    'sheet'    'freq_mtmfft_trl'               'DICS_fixedori'            
%    'sheet'    'freq_mtmfft_trl'               'PCC_keepall'              
%    'sheet'    'freq_mtmfft_trl'               'PCC_keepall_rawtrial'     
%    'sheet'    'freq_mtmfft_trl'               'PCC_keepnothing'          
%    'sheet'    'freq_mtmfft_trl'               'PCC_keepnothing_rawtrial' 
%    'sheet'    'freq_mtmfft_trl'               'PCC_refdip'               
%     'sheet'    'freq_mtmfft'                   'DICS_keepall'
%     'sheet'    'freq_mtmfft'                   'DICS_keepall_rawtrial'
%     'sheet'    'freq_mtmfft'                   'DICS_keepnothing'
%     'sheet'    'freq_mtmfft'                   'DICS_keepnothing_rawtrial'
%     'sheet'    'freq_mtmfft'                   'DICS_refdip'
%     'sheet'    'freq_mtmfft'                   'DICS_refchan'
%     'sheet'    'freq_mtmfft'                   'DICS_realfilter'
%     'sheet'    'freq_mtmfft'                   'DICS_fixedori'
%     'sheet'    'freq_mtmfft'                   'MNE_keepall'
%     'sheet'    'freq_mtmfft'                   'MNE_keepnothing'
%     'sheet'    'freq_mtmfft'                   'MNE_keepall_rawtrial'
%     'sheet'    'freq_mtmfft'                   'MNE_keepnothing_rawtrial'
%     'sheet'    'freq_mtmfft'                   'DICS_keepall'
%     'sheet'    'freq_mtmfft'                   'DICS_keepall_rawtrial'
%     'sheet'    'freq_mtmfft'                   'DICS_keepnothing'
%     'sheet'    'freq_mtmfft'                   'DICS_keepnothing_rawtrial'
%     'sheet'    'freq_mtmfft'                   'DICS_refdip'
%     'sheet'    'freq_mtmfft'                   'DICS_refchan'
%     'sheet'    'freq_mtmfft'                   'DICS_realfilter'
%     'sheet'    'freq_mtmfft'                   'DICS_fixedori'
%     'sheet'    'freq_mtmfft'                   'PCC_keepall'
%     'sheet'    'freq_mtmfft'                   'PCC_keepall_rawtrial'
%     'sheet'    'freq_mtmfft'                   'PCC_keepnothing'
%     'sheet'    'freq_mtmfft'                   'PCC_keepnothing_rawtrial'
%     'sheet'    'freq_mtmfft'                   'PCC_refdip'
%     'sheet'    'freq_mtmconvol_trl'            'DICS_keepall'             
%     'sheet'    'freq_mtmconvol_trl'            'DICS_keepall_rawtrial'    
%     'sheet'    'freq_mtmconvol_trl'            'DICS_keepnothing'         
%     'sheet'    'freq_mtmconvol_trl'            'DICS_keepnothing_rawtrial'
%     'sheet'    'freq_mtmconvol_trl'            'DICS_refdip'              
%     'sheet'    'freq_mtmconvol_trl'            'DICS_refchan'             
%     'sheet'    'freq_mtmconvol_trl'            'DICS_realfilter'          
%     'sheet'    'freq_mtmconvol_trl'            'DICS_fixedori'            
%     'sheet'    'freq_mtmconvol_trl'            'MNE_keepall'              
%     'sheet'    'freq_mtmconvol_trl'            'MNE_keepnothing'          
%     'sheet'    'freq_mtmconvol_trl'            'MNE_keepall_rawtrial'     
%     'sheet'    'freq_mtmconvol_trl'            'MNE_keepnothing_rawtrial' 
%      'sheet'    'freq_mtmconvol_trl'            'DICS_keepall'             
%     'sheet'    'freq_mtmconvol_trl'            'DICS_keepall_rawtrial'    
%     'sheet'    'freq_mtmconvol_trl'            'DICS_keepnothing'         
%     'sheet'    'freq_mtmconvol_trl'            'DICS_keepnothing_rawtrial'
%     'sheet'    'freq_mtmconvol_trl'            'DICS_refdip'              
%     'sheet'    'freq_mtmconvol_trl'            'DICS_refchan'             
%     'sheet'    'freq_mtmconvol_trl'            'DICS_realfilter'          
%     'sheet'    'freq_mtmconvol_trl'            'DICS_fixedori'            
%     'sheet'    'freq_mtmconvol_trl'            'PCC_keepall'              
%     'sheet'    'freq_mtmconvol_trl'            'PCC_keepall_rawtrial'     
%     'sheet'    'freq_mtmconvol_trl'            'PCC_keepnothing'          
%     'sheet'    'freq_mtmconvol_trl'            'PCC_keepnothing_rawtrial' 
%     'sheet'    'freq_mtmconvol_trl'            'PCC_refdip'               
%     'sheet'    'freq_mtmconvol'                'DICS_keepall'             
%     'sheet'    'freq_mtmconvol'                'DICS_keepall_rawtrial'    
%     'sheet'    'freq_mtmconvol'                'DICS_keepnothing'         
%     'sheet'    'freq_mtmconvol'                'DICS_keepnothing_rawtrial'
%     'sheet'    'freq_mtmconvol'                'DICS_refdip'              
%     'sheet'    'freq_mtmconvol'                'DICS_refchan'             
%     'sheet'    'freq_mtmconvol'                'DICS_realfilter'          
%     'sheet'    'freq_mtmconvol'                'DICS_fixedori'            
%     'sheet'    'freq_mtmconvol'                'MNE_keepall'              
%     'sheet'    'freq_mtmconvol'                'MNE_keepnothing'          
%     'sheet'    'freq_mtmconvol'                'MNE_keepall_rawtrial'     
%     'sheet'    'freq_mtmconvol'                'MNE_keepnothing_rawtrial' 
%      'sheet'    'freq_mtmconvol'                'DICS_keepall'             
%     'sheet'    'freq_mtmconvol'                'DICS_keepall_rawtrial'    
%     'sheet'    'freq_mtmconvol'                'DICS_keepnothing'         
%     'sheet'    'freq_mtmconvol'                'DICS_keepnothing_rawtrial'
%     'sheet'    'freq_mtmconvol'                'DICS_refdip'              
%     'sheet'    'freq_mtmconvol'                'DICS_refchan'             
%     'sheet'    'freq_mtmconvol'                'DICS_realfilter'          
%     'sheet'    'freq_mtmconvol'                'DICS_fixedori'            
%     'sheet'    'freq_mtmconvol'                'PCC_keepall'              
%     'sheet'    'freq_mtmconvol'                'PCC_keepall_rawtrial'     
%     'sheet'    'freq_mtmconvol'                'PCC_keepnothing'          
%     'sheet'    'freq_mtmconvol'                'PCC_keepnothing_rawtrial' 
%     'sheet'    'freq_mtmconvol'                'PCC_refdip'               
    'sheet'    'timelock'                      'MNE_keepall'              
    'sheet'    'timelock'                      'MNE_keepnothing'          
%    'sheet'    'timelock'                      'MNE_keepall_rawtrial'     
%    'sheet'    'timelock'                      'MNE_keepnothing_rawtrial' 
    'sheet'    'timelock'                      'LCMV_keepall'             
    'sheet'    'timelock'                      'LCMV_keepnothing'         
%    'sheet'    'timelock'                      'LCMV_keepall_rawtrial'    
%    'sheet'    'timelock'                      'LCMV_keepnothing_rawtrial'
    'sheet'    'timelock_trl'                  'MNE_keepall'              
    'sheet'    'timelock_trl'                  'MNE_keepnothing'          
    'sheet'    'timelock_trl'                  'MNE_keepall_rawtrial'     
    'sheet'    'timelock_trl'                  'MNE_keepnothing_rawtrial' 
    'sheet'    'timelock_trl'                  'LCMV_keepall'             
    'sheet'    'timelock_trl'                  'LCMV_keepnothing'         
    'sheet'    'timelock_trl'                  'LCMV_keepall_rawtrial'    
    'sheet'    'timelock_trl'                  'LCMV_keepnothing_rawtrial'
    'sheet'    'timelock_cov'                  'MNE_keepall'              
    'sheet'    'timelock_cov'                  'MNE_keepnothing'          
%    'sheet'    'timelock_cov'                  'MNE_keepall_rawtrial'     
%    'sheet'    'timelock_cov'                  'MNE_keepnothing_rawtrial' 
    'sheet'    'timelock_cov'                  'LCMV_keepall'             
    'sheet'    'timelock_cov'                  'LCMV_keepnothing'         
%    'sheet'    'timelock_cov'                  'LCMV_keepall_rawtrial'    
%    'sheet'    'timelock_cov'                  'LCMV_keepnothing_rawtrial'
    'sheet'    'timelock_cov_trl'              'MNE_keepall'              
    'sheet'    'timelock_cov_trl'              'MNE_keepnothing'          
    'sheet'    'timelock_cov_trl'              'MNE_keepall_rawtrial'     
    'sheet'    'timelock_cov_trl'              'MNE_keepnothing_rawtrial' 
    'sheet'    'timelock_cov_trl'              'LCMV_keepall'             
    'sheet'    'timelock_cov_trl'              'LCMV_keepnothing'         
    'sheet'    'timelock_cov_trl'              'LCMV_keepall_rawtrial'    
    'sheet'    'timelock_cov_trl'              'LCMV_keepnothing_rawtrial'
    'grid'     'freq_mtmfft_fourier_trl'       'DICS_keepall'             
    'grid'     'freq_mtmfft_fourier_trl'       'DICS_keepall_rawtrial'    
    'grid'     'freq_mtmfft_fourier_trl'       'DICS_keepnothing'         
    'grid'     'freq_mtmfft_fourier_trl'       'DICS_keepnothing_rawtrial'
    'grid'     'freq_mtmfft_fourier_trl'       'DICS_refdip'              
    'grid'     'freq_mtmfft_fourier_trl'       'DICS_refchan'             
    'grid'     'freq_mtmfft_fourier_trl'       'DICS_realfilter'          
    'grid'     'freq_mtmfft_fourier_trl'       'DICS_fixedori'            
    'grid'     'freq_mtmfft_fourier_trl'       'MNE_keepall'              
    'grid'     'freq_mtmfft_fourier_trl'       'MNE_keepnothing'          
    'grid'     'freq_mtmfft_fourier_trl'       'MNE_keepall_rawtrial'     
    'grid'     'freq_mtmfft_fourier_trl'       'MNE_keepnothing_rawtrial' 
    'grid'     'freq_mtmfft_fourier_trl'       'DICS_keepall'             
    'grid'     'freq_mtmfft_fourier_trl'       'DICS_keepall_rawtrial'    
    'grid'     'freq_mtmfft_fourier_trl'       'DICS_keepnothing'         
    'grid'     'freq_mtmfft_fourier_trl'       'DICS_keepnothing_rawtrial'
    'grid'     'freq_mtmfft_fourier_trl'       'DICS_refdip'              
    'grid'     'freq_mtmfft_fourier_trl'       'DICS_refchan'             
    'grid'     'freq_mtmfft_fourier_trl'       'DICS_realfilter'          
    'grid'     'freq_mtmfft_fourier_trl'       'DICS_fixedori'            
    'grid'     'freq_mtmfft_fourier_trl'       'PCC_keepall'              
    'grid'     'freq_mtmfft_fourier_trl'       'PCC_keepall_rawtrial'     
    'grid'     'freq_mtmfft_fourier_trl'       'PCC_keepnothing'          
    'grid'     'freq_mtmfft_fourier_trl'       'PCC_keepnothing_rawtrial' 
    'grid'     'freq_mtmfft_fourier_trl'       'PCC_refdip'               
    'grid'     'freq_mtmconvol_fourier_trl'    'DICS_keepall'             
    'grid'     'freq_mtmconvol_fourier_trl'    'DICS_keepall_rawtrial'    
    'grid'     'freq_mtmconvol_fourier_trl'    'DICS_keepnothing'         
    'grid'     'freq_mtmconvol_fourier_trl'    'DICS_keepnothing_rawtrial'
    'grid'     'freq_mtmconvol_fourier_trl'    'DICS_refdip'              
    'grid'     'freq_mtmconvol_fourier_trl'    'DICS_refchan'             
    'grid'     'freq_mtmconvol_fourier_trl'    'DICS_realfilter'          
    'grid'     'freq_mtmconvol_fourier_trl'    'DICS_fixedori'            
    'grid'     'freq_mtmconvol_fourier_trl'    'MNE_keepall'              
    'grid'     'freq_mtmconvol_fourier_trl'    'MNE_keepnothing'          
    'grid'     'freq_mtmconvol_fourier_trl'    'MNE_keepall_rawtrial'     
    'grid'     'freq_mtmconvol_fourier_trl'    'MNE_keepnothing_rawtrial' 
     'grid'     'freq_mtmconvol_fourier_trl'    'DICS_keepall'             
    'grid'     'freq_mtmconvol_fourier_trl'    'DICS_keepall_rawtrial'    
    'grid'     'freq_mtmconvol_fourier_trl'    'DICS_keepnothing'         
    'grid'     'freq_mtmconvol_fourier_trl'    'DICS_keepnothing_rawtrial'
    'grid'     'freq_mtmconvol_fourier_trl'    'DICS_refdip'              
    'grid'     'freq_mtmconvol_fourier_trl'    'DICS_refchan'             
    'grid'     'freq_mtmconvol_fourier_trl'    'DICS_realfilter'          
    'grid'     'freq_mtmconvol_fourier_trl'    'DICS_fixedori'            
    'grid'     'freq_mtmconvol_fourier_trl'    'PCC_keepall'              
    'grid'     'freq_mtmconvol_fourier_trl'    'PCC_keepall_rawtrial'     
    'grid'     'freq_mtmconvol_fourier_trl'    'PCC_keepnothing'          
    'grid'     'freq_mtmconvol_fourier_trl'    'PCC_keepnothing_rawtrial' 
    'grid'     'freq_mtmconvol_fourier_trl'    'PCC_refdip'               
%     'grid'     'freq_mtmfft_trl'               'DICS_keepall'             
%     'grid'     'freq_mtmfft_trl'               'DICS_keepall_rawtrial'    
%     'grid'     'freq_mtmfft_trl'               'DICS_keepnothing'         
%     'grid'     'freq_mtmfft_trl'               'DICS_keepnothing_rawtrial'
%     'grid'     'freq_mtmfft_trl'               'DICS_refdip'              
%     'grid'     'freq_mtmfft_trl'               'DICS_refchan'             
%     'grid'     'freq_mtmfft_trl'               'DICS_realfilter'          
%     'grid'     'freq_mtmfft_trl'               'DICS_fixedori'            
%     'grid'     'freq_mtmfft_trl'               'MNE_keepall'              
%     'grid'     'freq_mtmfft_trl'               'MNE_keepnothing'          
%     'grid'     'freq_mtmfft_trl'               'MNE_keepall_rawtrial'     
%     'grid'     'freq_mtmfft_trl'               'MNE_keepnothing_rawtrial' 
%     'grid'     'freq_mtmfft_trl'               'DICS_keepall'             
%     'grid'     'freq_mtmfft_trl'               'DICS_keepall_rawtrial'    
%     'grid'     'freq_mtmfft_trl'               'DICS_keepnothing'         
%     'grid'     'freq_mtmfft_trl'               'DICS_keepnothing_rawtrial'
%     'grid'     'freq_mtmfft_trl'               'DICS_refdip'              
%     'grid'     'freq_mtmfft_trl'               'DICS_refchan'             
%     'grid'     'freq_mtmfft_trl'               'DICS_realfilter'          
%     'grid'     'freq_mtmfft_trl'               'DICS_fixedori'            
%     'grid'     'freq_mtmfft_trl'               'PCC_keepall'              
%     'grid'     'freq_mtmfft_trl'               'PCC_keepall_rawtrial'     
%     'grid'     'freq_mtmfft_trl'               'PCC_keepnothing'          
%     'grid'     'freq_mtmfft_trl'               'PCC_keepnothing_rawtrial' 
%     'grid'     'freq_mtmfft_trl'               'PCC_refdip'               
%     'grid'     'freq_mtmfft'                   'DICS_keepall'             
%     'grid'     'freq_mtmfft'                   'DICS_keepall_rawtrial'    
%     'grid'     'freq_mtmfft'                   'DICS_keepnothing'         
%     'grid'     'freq_mtmfft'                   'DICS_keepnothing_rawtrial'
%     'grid'     'freq_mtmfft'                   'DICS_refdip'              
%     'grid'     'freq_mtmfft'                   'DICS_refchan'             
%     'grid'     'freq_mtmfft'                   'DICS_realfilter'          
%     'grid'     'freq_mtmfft'                   'DICS_fixedori'            
%     'grid'     'freq_mtmfft'                   'MNE_keepall'              
%     'grid'     'freq_mtmfft'                   'MNE_keepnothing'          
%     'grid'     'freq_mtmfft'                   'MNE_keepall_rawtrial'     
%     'grid'     'freq_mtmfft'                   'MNE_keepnothing_rawtrial' 
%     'grid'     'freq_mtmfft'                   'DICS_keepall'             
%     'grid'     'freq_mtmfft'                   'DICS_keepall_rawtrial'    
%     'grid'     'freq_mtmfft'                   'DICS_keepnothing'         
%     'grid'     'freq_mtmfft'                   'DICS_keepnothing_rawtrial'
%     'grid'     'freq_mtmfft'                   'DICS_refdip'              
%     'grid'     'freq_mtmfft'                   'DICS_refchan'             
%     'grid'     'freq_mtmfft'                   'DICS_realfilter'          
%     'grid'     'freq_mtmfft'                   'DICS_fixedori'            
%     'grid'     'freq_mtmfft'                   'PCC_keepall'              
%     'grid'     'freq_mtmfft'                   'PCC_keepall_rawtrial'     
%     'grid'     'freq_mtmfft'                   'PCC_keepnothing'          
%     'grid'     'freq_mtmfft'                   'PCC_keepnothing_rawtrial' 
%     'grid'     'freq_mtmfft'                   'PCC_refdip'               
%     'grid'     'freq_mtmconvol_trl'            'DICS_keepall'             
%     'grid'     'freq_mtmconvol_trl'            'DICS_keepall_rawtrial'    
%     'grid'     'freq_mtmconvol_trl'            'DICS_keepnothing'         
%     'grid'     'freq_mtmconvol_trl'            'DICS_keepnothing_rawtrial'
%     'grid'     'freq_mtmconvol_trl'            'DICS_refdip'              
%     'grid'     'freq_mtmconvol_trl'            'DICS_refchan'             
%     'grid'     'freq_mtmconvol_trl'            'DICS_realfilter'          
%     'grid'     'freq_mtmconvol_trl'            'DICS_fixedori'            
%     'grid'     'freq_mtmconvol_trl'            'MNE_keepall'              
%     'grid'     'freq_mtmconvol_trl'            'MNE_keepnothing'          
%     'grid'     'freq_mtmconvol_trl'            'MNE_keepall_rawtrial'     
%     'grid'     'freq_mtmconvol_trl'            'MNE_keepnothing_rawtrial' 
%    'grid'     'freq_mtmconvol_trl'            'DICS_keepall'             
%     'grid'     'freq_mtmconvol_trl'            'DICS_keepall_rawtrial'    
%     'grid'     'freq_mtmconvol_trl'            'DICS_keepnothing'         
%     'grid'     'freq_mtmconvol_trl'            'DICS_keepnothing_rawtrial'
%     'grid'     'freq_mtmconvol_trl'            'DICS_refdip'              
%     'grid'     'freq_mtmconvol_trl'            'DICS_refchan'             
%     'grid'     'freq_mtmconvol_trl'            'DICS_realfilter'          
%     'grid'     'freq_mtmconvol_trl'            'DICS_fixedori'            
%     'grid'     'freq_mtmconvol_trl'            'PCC_keepall'              
%     'grid'     'freq_mtmconvol_trl'            'PCC_keepall_rawtrial'     
%     'grid'     'freq_mtmconvol_trl'            'PCC_keepnothing'          
%     'grid'     'freq_mtmconvol_trl'            'PCC_keepnothing_rawtrial' 
%     'grid'     'freq_mtmconvol_trl'            'PCC_refdip'               
%     'grid'     'freq_mtmconvol'                'DICS_keepall'             
%     'grid'     'freq_mtmconvol'                'DICS_keepall_rawtrial'    
%     'grid'     'freq_mtmconvol'                'DICS_keepnothing'         
%     'grid'     'freq_mtmconvol'                'DICS_keepnothing_rawtrial'
%     'grid'     'freq_mtmconvol'                'DICS_refdip'              
%     'grid'     'freq_mtmconvol'                'DICS_refchan'             
%     'grid'     'freq_mtmconvol'                'DICS_realfilter'          
%     'grid'     'freq_mtmconvol'                'DICS_fixedori'            
%     'grid'     'freq_mtmconvol'                'MNE_keepall'              
%     'grid'     'freq_mtmconvol'                'MNE_keepnothing'          
%     'grid'     'freq_mtmconvol'                'MNE_keepall_rawtrial'     
%     'grid'     'freq_mtmconvol'                'MNE_keepnothing_rawtrial' 
%     'grid'     'freq_mtmconvol'                'DICS_keepall'             
%     'grid'     'freq_mtmconvol'                'DICS_keepall_rawtrial'    
%     'grid'     'freq_mtmconvol'                'DICS_keepnothing'         
%     'grid'     'freq_mtmconvol'                'DICS_keepnothing_rawtrial'
%     'grid'     'freq_mtmconvol'                'DICS_refdip'              
%     'grid'     'freq_mtmconvol'                'DICS_refchan'             
%     'grid'     'freq_mtmconvol'                'DICS_realfilter'          
%     'grid'     'freq_mtmconvol'                'DICS_fixedori'            
%     'grid'     'freq_mtmconvol'                'PCC_keepall'              
%     'grid'     'freq_mtmconvol'                'PCC_keepall_rawtrial'     
%     'grid'     'freq_mtmconvol'                'PCC_keepnothing'          
%     'grid'     'freq_mtmconvol'                'PCC_keepnothing_rawtrial' 
%     'grid'     'freq_mtmconvol'                'PCC_refdip'               
    'grid'     'timelock'                      'MNE_keepall'              
    'grid'     'timelock'                      'MNE_keepnothing'          
%    'grid'     'timelock'                      'MNE_keepall_rawtrial'     
%    'grid'     'timelock'                      'MNE_keepnothing_rawtrial' 
    'grid'     'timelock'                      'LCMV_keepall'             
    'grid'     'timelock'                      'LCMV_keepnothing'         
%    'grid'     'timelock'                      'LCMV_keepall_rawtrial'    
%    'grid'     'timelock'                      'LCMV_keepnothing_rawtrial'
    'grid'     'timelock_trl'                  'MNE_keepall'              
    'grid'     'timelock_trl'                  'MNE_keepnothing'          
    'grid'     'timelock_trl'                  'MNE_keepall_rawtrial'     
    'grid'     'timelock_trl'                  'MNE_keepnothing_rawtrial' 
    'grid'     'timelock_trl'                  'LCMV_keepall'             
    'grid'     'timelock_trl'                  'LCMV_keepnothing'         
    'grid'     'timelock_trl'                  'LCMV_keepall_rawtrial'    
    'grid'     'timelock_trl'                  'LCMV_keepnothing_rawtrial'
    'grid'     'timelock_cov'                  'MNE_keepall'              
    'grid'     'timelock_cov'                  'MNE_keepnothing'          
%    'grid'     'timelock_cov'                  'MNE_keepall_rawtrial'     
%    'grid'     'timelock_cov'                  'MNE_keepnothing_rawtrial' 
    'grid'     'timelock_cov'                  'LCMV_keepall'             
    'grid'     'timelock_cov'                  'LCMV_keepnothing'         
%    'grid'     'timelock_cov'                  'LCMV_keepall_rawtrial'    
%    'grid'     'timelock_cov'                  'LCMV_keepnothing_rawtrial'
    'grid'     'timelock_cov_trl'              'MNE_keepall'              
    'grid'     'timelock_cov_trl'              'MNE_keepnothing'          
    'grid'     'timelock_cov_trl'              'MNE_keepall_rawtrial'     
    'grid'     'timelock_cov_trl'              'MNE_keepnothing_rawtrial' 
    'grid'     'timelock_cov_trl'              'LCMV_keepall'             
    'grid'     'timelock_cov_trl'              'LCMV_keepnothing'         
    'grid'     'timelock_cov_trl'              'LCMV_keepall_rawtrial'    
    'grid'     'timelock_cov_trl'              'LCMV_keepnothing_rawtrial'
    'roi'      'freq_mtmfft_fourier_trl'       'DICS_keepall'             
    'roi'      'freq_mtmfft_fourier_trl'       'DICS_keepall_rawtrial'    
    'roi'      'freq_mtmfft_fourier_trl'       'DICS_keepnothing'         
    'roi'      'freq_mtmfft_fourier_trl'       'DICS_keepnothing_rawtrial'
    'roi'      'freq_mtmfft_fourier_trl'       'DICS_refdip'              
    'roi'      'freq_mtmfft_fourier_trl'       'DICS_refchan'             
    'roi'      'freq_mtmfft_fourier_trl'       'DICS_realfilter'          
    'roi'      'freq_mtmfft_fourier_trl'       'DICS_fixedori'            
    'roi'      'freq_mtmfft_fourier_trl'       'MNE_keepall'              
    'roi'      'freq_mtmfft_fourier_trl'       'MNE_keepnothing'          
    'roi'      'freq_mtmfft_fourier_trl'       'MNE_keepall_rawtrial'     
    'roi'      'freq_mtmfft_fourier_trl'       'MNE_keepnothing_rawtrial' 
    'roi'      'freq_mtmfft_fourier_trl'       'DICS_keepall'             
    'roi'      'freq_mtmfft_fourier_trl'       'DICS_keepall_rawtrial'    
    'roi'      'freq_mtmfft_fourier_trl'       'DICS_keepnothing'         
    'roi'      'freq_mtmfft_fourier_trl'       'DICS_keepnothing_rawtrial'
    'roi'      'freq_mtmfft_fourier_trl'       'DICS_refdip'              
    'roi'      'freq_mtmfft_fourier_trl'       'DICS_refchan'             
    'roi'      'freq_mtmfft_fourier_trl'       'DICS_realfilter'          
    'roi'      'freq_mtmfft_fourier_trl'       'DICS_fixedori'            
    'roi'      'freq_mtmfft_fourier_trl'       'PCC_keepall'              
    'roi'      'freq_mtmfft_fourier_trl'       'PCC_keepall_rawtrial'     
    'roi'      'freq_mtmfft_fourier_trl'       'PCC_keepnothing'          
    'roi'      'freq_mtmfft_fourier_trl'       'PCC_keepnothing_rawtrial' 
    'roi'      'freq_mtmfft_fourier_trl'       'PCC_refdip'               
    'roi'      'freq_mtmconvol_fourier_trl'    'DICS_keepall'             
    'roi'      'freq_mtmconvol_fourier_trl'    'DICS_keepall_rawtrial'    
    'roi'      'freq_mtmconvol_fourier_trl'    'DICS_keepnothing'         
    'roi'      'freq_mtmconvol_fourier_trl'    'DICS_keepnothing_rawtrial'
    'roi'      'freq_mtmconvol_fourier_trl'    'DICS_refdip'              
    'roi'      'freq_mtmconvol_fourier_trl'    'DICS_refchan'             
    'roi'      'freq_mtmconvol_fourier_trl'    'DICS_realfilter'          
    'roi'      'freq_mtmconvol_fourier_trl'    'DICS_fixedori'            
    'roi'      'freq_mtmconvol_fourier_trl'    'MNE_keepall'              
    'roi'      'freq_mtmconvol_fourier_trl'    'MNE_keepnothing'          
    'roi'      'freq_mtmconvol_fourier_trl'    'MNE_keepall_rawtrial'     
    'roi'      'freq_mtmconvol_fourier_trl'    'MNE_keepnothing_rawtrial' 
    'roi'      'freq_mtmconvol_fourier_trl'    'DICS_keepall'             
    'roi'      'freq_mtmconvol_fourier_trl'    'DICS_keepall_rawtrial'    
    'roi'      'freq_mtmconvol_fourier_trl'    'DICS_keepnothing'         
    'roi'      'freq_mtmconvol_fourier_trl'    'DICS_keepnothing_rawtrial'
    'roi'      'freq_mtmconvol_fourier_trl'    'DICS_refdip'              
    'roi'      'freq_mtmconvol_fourier_trl'    'DICS_refchan'             
    'roi'      'freq_mtmconvol_fourier_trl'    'DICS_realfilter'          
    'roi'      'freq_mtmconvol_fourier_trl'    'DICS_fixedori'            
    'roi'      'freq_mtmconvol_fourier_trl'    'PCC_keepall'              
    'roi'      'freq_mtmconvol_fourier_trl'    'PCC_keepall_rawtrial'     
    'roi'      'freq_mtmconvol_fourier_trl'    'PCC_keepnothing'          
    'roi'      'freq_mtmconvol_fourier_trl'    'PCC_keepnothing_rawtrial' 
    'roi'      'freq_mtmconvol_fourier_trl'    'PCC_refdip'               
%     'roi'      'freq_mtmfft_trl'               'DICS_keepall'             
%     'roi'      'freq_mtmfft_trl'               'DICS_keepall_rawtrial'    
%     'roi'      'freq_mtmfft_trl'               'DICS_keepnothing'         
%     'roi'      'freq_mtmfft_trl'               'DICS_keepnothing_rawtrial'
%     'roi'      'freq_mtmfft_trl'               'DICS_refdip'              
%     'roi'      'freq_mtmfft_trl'               'DICS_refchan'             
%     'roi'      'freq_mtmfft_trl'               'DICS_realfilter'          
%     'roi'      'freq_mtmfft_trl'               'DICS_fixedori'            
%     'roi'      'freq_mtmfft_trl'               'MNE_keepall'              
%     'roi'      'freq_mtmfft_trl'               'MNE_keepnothing'          
%     'roi'      'freq_mtmfft_trl'               'MNE_keepall_rawtrial'     
%     'roi'      'freq_mtmfft_trl'               'MNE_keepnothing_rawtrial' 
%    'roi'      'freq_mtmfft_trl'               'DICS_keepall'             
%     'roi'      'freq_mtmfft_trl'               'DICS_keepall_rawtrial'    
%     'roi'      'freq_mtmfft_trl'               'DICS_keepnothing'         
%     'roi'      'freq_mtmfft_trl'               'DICS_keepnothing_rawtrial'
%     'roi'      'freq_mtmfft_trl'               'DICS_refdip'              
%     'roi'      'freq_mtmfft_trl'               'DICS_refchan'             
%     'roi'      'freq_mtmfft_trl'               'DICS_realfilter'          
%     'roi'      'freq_mtmfft_trl'               'DICS_fixedori'            
%     'roi'      'freq_mtmfft_trl'               'PCC_keepall'              
%     'roi'      'freq_mtmfft_trl'               'PCC_keepall_rawtrial'     
%     'roi'      'freq_mtmfft_trl'               'PCC_keepnothing'          
%     'roi'      'freq_mtmfft_trl'               'PCC_keepnothing_rawtrial' 
%     'roi'      'freq_mtmfft_trl'               'PCC_refdip'               
%     'roi'      'freq_mtmfft'                   'DICS_keepall'             
%     'roi'      'freq_mtmfft'                   'DICS_keepall_rawtrial'    
%     'roi'      'freq_mtmfft'                   'DICS_keepnothing'         
%     'roi'      'freq_mtmfft'                   'DICS_keepnothing_rawtrial'
%     'roi'      'freq_mtmfft'                   'DICS_refdip'              
%     'roi'      'freq_mtmfft'                   'DICS_refchan'             
%     'roi'      'freq_mtmfft'                   'DICS_realfilter'          
%     'roi'      'freq_mtmfft'                   'DICS_fixedori'            
%     'roi'      'freq_mtmfft'                   'MNE_keepall'              
%     'roi'      'freq_mtmfft'                   'MNE_keepnothing'          
%     'roi'      'freq_mtmfft'                   'MNE_keepall_rawtrial'     
%     'roi'      'freq_mtmfft'                   'MNE_keepnothing_rawtrial' 
%     'roi'      'freq_mtmfft'                   'DICS_keepall'             
%     'roi'      'freq_mtmfft'                   'DICS_keepall_rawtrial'    
%     'roi'      'freq_mtmfft'                   'DICS_keepnothing'         
%     'roi'      'freq_mtmfft'                   'DICS_keepnothing_rawtrial'
%     'roi'      'freq_mtmfft'                   'DICS_refdip'              
%     'roi'      'freq_mtmfft'                   'DICS_refchan'             
%     'roi'      'freq_mtmfft'                   'DICS_realfilter'          
%     'roi'      'freq_mtmfft'                   'DICS_fixedori'            
%     'roi'      'freq_mtmfft'                   'PCC_keepall'              
%     'roi'      'freq_mtmfft'                   'PCC_keepall_rawtrial'     
%     'roi'      'freq_mtmfft'                   'PCC_keepnothing'          
%     'roi'      'freq_mtmfft'                   'PCC_keepnothing_rawtrial' 
%     'roi'      'freq_mtmfft'                   'PCC_refdip'               
%     'roi'      'freq_mtmconvol_trl'            'DICS_keepall'             
%     'roi'      'freq_mtmconvol_trl'            'DICS_keepall_rawtrial'    
%     'roi'      'freq_mtmconvol_trl'            'DICS_keepnothing'         
%     'roi'      'freq_mtmconvol_trl'            'DICS_keepnothing_rawtrial'
%     'roi'      'freq_mtmconvol_trl'            'DICS_refdip'              
%     'roi'      'freq_mtmconvol_trl'            'DICS_refchan'             
%     'roi'      'freq_mtmconvol_trl'            'DICS_realfilter'          
%     'roi'      'freq_mtmconvol_trl'            'DICS_fixedori'            
%     'roi'      'freq_mtmconvol_trl'            'MNE_keepall'              
%     'roi'      'freq_mtmconvol_trl'            'MNE_keepnothing'          
%     'roi'      'freq_mtmconvol_trl'            'MNE_keepall_rawtrial'     
%     'roi'      'freq_mtmconvol_trl'            'MNE_keepnothing_rawtrial' 
%     'roi'      'freq_mtmconvol_trl'            'DICS_keepall'             
%     'roi'      'freq_mtmconvol_trl'            'DICS_keepall_rawtrial'    
%     'roi'      'freq_mtmconvol_trl'            'DICS_keepnothing'         
%     'roi'      'freq_mtmconvol_trl'            'DICS_keepnothing_rawtrial'
%     'roi'      'freq_mtmconvol_trl'            'DICS_refdip'              
%     'roi'      'freq_mtmconvol_trl'            'DICS_refchan'             
%     'roi'      'freq_mtmconvol_trl'            'DICS_realfilter'          
%     'roi'      'freq_mtmconvol_trl'            'DICS_fixedori'            
%     'roi'      'freq_mtmconvol_trl'            'PCC_keepall'              
%     'roi'      'freq_mtmconvol_trl'            'PCC_keepall_rawtrial'     
%     'roi'      'freq_mtmconvol_trl'            'PCC_keepnothing'          
%     'roi'      'freq_mtmconvol_trl'            'PCC_keepnothing_rawtrial' 
%     'roi'      'freq_mtmconvol_trl'            'PCC_refdip'               
%     'roi'      'freq_mtmconvol'                'DICS_keepall'             
%     'roi'      'freq_mtmconvol'                'DICS_keepall_rawtrial'    
%     'roi'      'freq_mtmconvol'                'DICS_keepnothing'         
%     'roi'      'freq_mtmconvol'                'DICS_keepnothing_rawtrial'
%     'roi'      'freq_mtmconvol'                'DICS_refdip'              
%     'roi'      'freq_mtmconvol'                'DICS_refchan'             
%     'roi'      'freq_mtmconvol'                'DICS_realfilter'          
%     'roi'      'freq_mtmconvol'                'DICS_fixedori'            
%     'roi'      'freq_mtmconvol'                'MNE_keepall'              
%     'roi'      'freq_mtmconvol'                'MNE_keepnothing'          
%     'roi'      'freq_mtmconvol'                'MNE_keepall_rawtrial'     
%     'roi'      'freq_mtmconvol'                'MNE_keepnothing_rawtrial' 
%     'roi'      'freq_mtmconvol'                'DICS_keepall'             
%     'roi'      'freq_mtmconvol'                'DICS_keepall_rawtrial'    
%     'roi'      'freq_mtmconvol'                'DICS_keepnothing'         
%     'roi'      'freq_mtmconvol'                'DICS_keepnothing_rawtrial'
%     'roi'      'freq_mtmconvol'                'DICS_refdip'              
%     'roi'      'freq_mtmconvol'                'DICS_refchan'             
%     'roi'      'freq_mtmconvol'                'DICS_realfilter'          
%     'roi'      'freq_mtmconvol'                'DICS_fixedori'            
%     'roi'      'freq_mtmconvol'                'PCC_keepall'              
%     'roi'      'freq_mtmconvol'                'PCC_keepall_rawtrial'     
%     'roi'      'freq_mtmconvol'                'PCC_keepnothing'          
%     'roi'      'freq_mtmconvol'                'PCC_keepnothing_rawtrial' 
%     'roi'      'freq_mtmconvol'                'PCC_refdip'               
     'roi'      'timelock'                      'MNE_keepall'              
    'roi'      'timelock'                      'MNE_keepnothing'          
%    'roi'      'timelock'                      'MNE_keepall_rawtrial'     
%    'roi'      'timelock'                      'MNE_keepnothing_rawtrial' 
    'roi'      'timelock'                      'LCMV_keepall'             
    'roi'      'timelock'                      'LCMV_keepnothing'         
%    'roi'      'timelock'                      'LCMV_keepall_rawtrial'    
%    'roi'      'timelock'                      'LCMV_keepnothing_rawtrial'
     'roi'      'timelock_trl'                  'MNE_keepall'              
    'roi'      'timelock_trl'                  'MNE_keepnothing'          
    'roi'      'timelock_trl'                  'MNE_keepall_rawtrial'     
    'roi'      'timelock_trl'                  'MNE_keepnothing_rawtrial' 
    'roi'      'timelock_trl'                  'LCMV_keepall'             
    'roi'      'timelock_trl'                  'LCMV_keepnothing'         
    'roi'      'timelock_trl'                  'LCMV_keepall_rawtrial'    
    'roi'      'timelock_trl'                  'LCMV_keepnothing_rawtrial'
    'roi'      'timelock_cov'                  'MNE_keepall'              
    'roi'      'timelock_cov'                  'MNE_keepnothing'          
%    'roi'      'timelock_cov'                  'MNE_keepall_rawtrial'     
%    'roi'      'timelock_cov'                  'MNE_keepnothing_rawtrial' 
    'roi'      'timelock_cov'                  'LCMV_keepall'             
    'roi'      'timelock_cov'                  'LCMV_keepnothing'         
%    'roi'      'timelock_cov'                  'LCMV_keepall_rawtrial'    
%    'roi'      'timelock_cov'                  'LCMV_keepnothing_rawtrial'
    'roi'      'timelock_cov_trl'              'MNE_keepall'              
    'roi'      'timelock_cov_trl'              'MNE_keepnothing'          
    'roi'      'timelock_cov_trl'              'MNE_keepall_rawtrial'     
    'roi'      'timelock_cov_trl'              'MNE_keepnothing_rawtrial' 
    'roi'      'timelock_cov_trl'              'LCMV_keepall'             
    'roi'      'timelock_cov_trl'              'LCMV_keepnothing'         
    'roi'      'timelock_cov_trl'              'LCMV_keepall_rawtrial'    
    'roi'      'timelock_cov_trl'              'LCMV_keepnothing_rawtrial'
                 
};

