language: java
install: source /dev/stdin <<< "$(curl -sL https://ssd.mathworks.com/supportfiles/matlab-runner/install)"
script: matlab-runner --disableAutoInfiles --disableAutoOutfiles "disp('hello world')"
