language: java
install: source /dev/stdin <<< "$(curl -sL https://ssd.mathworks.com/supportfiles/matlab-runner/install)"
script: travis_wait matlab-runner --disableAutoOutfiles "ft_defaults; test_matlab_ci"
