blank_issues_enabled: false
contact_links:
  - name: FieldTrip community forum
    url: http://www.fieldtriptoolbox.org/discussion_list/
    about: Please ask questions about the use of the toolbox here.
  - name: Direct contact with the maintainers
    url: http://www.fieldtriptoolbox.org/contact/#contact
    about: Please use this for questions that are not suitable for public discussion.
