//COPYRIGHT © 2013 G.TEC MEDICAL ENGINEERING GMBH, AUSTRIA
#ifndef CONSTANTS_HPP_INCLUDED
#define CONSTANTS_HPP_INCLUDED

// COMMANDS:
#define CMD_GET_CONNECTED_DEVICES "2"
#define CMD_OPEN_DAQ_SESSION "3"
#define CMD_OPEN_DAQ_SESSION_EXCLUSIVELY "4"
#define CMD_CLOSE_DAQ_SESSION "5"
#define CMD_BECOME_CREATOR "6"
#define CMD_GET_SESSION_ID "7"
#define CMD_BECOME_PARTICIPANT "8"
#define CMD_START_ACQUISITION "9"
#define CMD_STOP_ACQUISITION "10"
#define CMD_START_STREAMING "11"
#define CMD_STOP_STREAMING "12"
#define CMD_GET_DATA_INFO "13"
#define CMD_GET_DATA "14"
#define CMD_SET_CONFIGURATION "15"
#define CMD_GET_CONFIGURATION "16"
#define CMD_DISCONNECT "22"
#define CMD_SETUP_STREAMING "30"
#define CMD_DEVICE_SPECIFIC_OPERATION "31"
#define CMD_DATA_READY_EVENT_THRESHOLD "33"

// STATUS CODES:
#define STATUS_COMMAND "1"
#define STATUS_SUCCESS "2"
#define STATUS_FAILURE "3"

// ERROR CODES:
#define ERROR_NO_ERROR "0"

// EVENT CODES
#define EVENT_HEARTBEAT_MISSING_SHUTDOWN "21"
#define EVENT_CONFIGURATION_CHANGED "23"
#define EVENT_DATA_ACQUISITION_STARTED "24"
#define EVENT_DATA_ACQUISITION_STOPPED "25"
#define EVENT_DATA_ACQUISITION_ERROR "26"
#define EVENT_SESSION_CREATOR_DIED "27"
#define EVENT_NEW_SESSION_CREATOR "28"
#define EVENT_SERVER_DIED "29"
#define EVENT_DEVICE_SPECIFIC_CALLBACK "32"
#define EVENT_DATA_READY "34"

#endif // CONSTANTS_HPP_INCLUDED
