#!/bin/sh

case `arch` in
    i686)
		bufex="/home/common/matlab/fieldtrip/realtime/bin/glnx86/buffer 1972"
        ;;
    x86_64)
		bufex="/home/common/matlab/fieldtrip/realtime/bin/glnxa64/buffer 1972"
        ;;
esac

xterm -T "Runnig FieldTrip buffer - press CTRL-C when done" -e $bufex &
matlab -r "addpath('/home/common/matlab/fieldtrip','/home/common/matlab/spm8'); ft_defaults; ft_omri_quality;"




